# Generated by Django 3.2.8 on 2021-11-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_rename_valores_gastos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gastos',
            new_name='Gasto',
        ),
    ]
